name: Deploy Node.js Backend App via PM2

on:
  push:
    branches: [main] # ya apni branch yahan daal sakte ho

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code

        uses: actions/checkout@v4

      - name: Use Node.js

        uses: actions/setup-node@v4

        with:
          node-version: "18"

      - name: Install frontend dependencies and build
        run: |
          cd ${{ github.workspace }}/apps/frontend
          npm install
          npm run build

      - name: Copy frontend build to backend
        run: |
          cp -r ${{ github.workspace }}/apps/frontend/dist/* ${{ github.workspace }}/apps/backend/src/dist/

      - name: Install backend dependencies
        run: |
          cd ${{ github.workspace }}/apps/backend
          npm install

      - name: Start or restart backend with PM2
        run: |
          cd ${{ github.workspace }}/apps/backend
          /usr/bin/pm2 start index.js --name rajbytextilepvt || /usr/bin/pm2 restart rajbytextilepvt